### ISSUE TITLE
ModuleNotFoundError: No module named 'models.dgcnn'

### ISSUE THREAD

**Issue by yongpan0715** [gabrieletiboni/paintnet#4]
Hi, you wrote from models.dgcnn import DGCNNDiscriminator in loss_handler.py, but I don't find dgcnn in the models folder?

**Comment by gabrieletiboni** [comment]
@yongpan0715 thank you for pointing out the import error!

I just pushed a fix to it, by including the dgcnn model in the `models` directory. However, keep in mind that the discriminator experiments are not documented in the readme file, nor in the original paper. These were extra experiments I conducted while working on the project, but turned out they were not working as expected.

I'll leave the issue open for now, let me know if you still get the error :)

**Comment by gabrieletiboni** [comment]
The fix should've solved the error, I'm closing the issue :)
